FormSystem/FormSystem/Controllers/BackStageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FormSystem.DBModel;
using FormSystem.Models;
using FormSystem.Functions;
using Newtonsoft.Json;
using System.Web.Security;

namespace FormSystem.Controllers
{
    [Authorize]
    public class BackStageController : Controller
    {
        #region Show Page
        /// <summary>表單管理頁</summary>
        /// <returns></returns>
        public ActionResult FormManager()
        {
            var InfoList = new FormDBModel().FormInfoes.OrderByDescending(f => f.CreateDate).ToList();
            return View(InfoList);
        }

        /// <summary>顯示常用問題頁面</summary>
        /// <returns></returns>
        public ActionResult FrequentlyQuestions()
        {
            // Reset Session
            Session["FrequentIndex"] = null;

            // Set Drop Down List
            ViewBag.SelectList = DALFunctions.QusetionsType();

            // Save data into viewbag
            ViewBag.FrequenList = DALFunctions.FrequentlyQuestionsList();

            return View(new FrenquenQuestion()); ;
        }

        /// <summary>表單的答案清單頁面</summary>
        /// <param name="fid"></param>
        /// <returns></returns>
        public ActionResult AnsList(string fid)
        {
            try
            {
                if (!Guid.TryParse(fid, out Guid FID))
                    throw new Exception("GUID Error");

                Session["FID"] = fid;

                List<AnsInfo> ansList = new List<AnsInfo>();

                foreach (var ans in DALFunctions.GetFormAns(FID))
                {
                    // choose first answer
                    string firstAns = ans.AnswerData.Split(';')[0];

                    // create new object and add to List
                    ansList.Add(
                        new AnsInfo
                        {
                            FormID = FID,
                            DataID = ans.DataID,
                            AnsHead = firstAns,
                            CreateDate = ans.CreateDate.ToString("yyyy-MM-dd HH:mm:ss")
                        }
                    );
                }
                return View(ansList);
            }
            catch (Exception ex)
            {
                return RedirectToAction("ErrorPage", "Home", new { errMsg = ex.ToString() });
            }
        }

        /// <summary>登出</summary>
        /// <returns></returns>
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
        #endregion

        #region Pagination Controllers
        /// <summary>表單管理分頁控制</summary>
        /// <param name="fLay"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult FormManagerPagination()
        {
            // Count how many item in DB
            int totalCount = new FormDBModel().FormInfoes.ToList().Count();
            int itemsPerPage = 5;

            // send html code
            IndexPagerModel indexHTML = new IndexPagerModel()
            {
                ShowFormsHTML = null,  // questions list
                PagniationHTML = ModelFunctions.PaginationHTML(totalCount, itemsPerPage), // pagination list
                MaxPage = totalCount % itemsPerPage == 0 ? totalCount / itemsPerPage : totalCount / itemsPerPage + 1, // max page number
                ItemsPerPage = itemsPerPage
            };

            return Json(indexHTML, JsonRequestBehavior.AllowGet);
        }

        /// <summary>常用問題分頁控制</summary>
        /// <param name="fLay"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult FreqQuestionPagination()
        {
            // Count how many item in DB
            int totalCount = new FormDBModel().FrenquenQuestions.ToList().Count();
            int itemsPerPage = 5;

            // send html code
            IndexPagerModel indexHTML = new IndexPagerModel()
            {
                ShowFormsHTML = null,  // questions list
                PagniationHTML = ModelFunctions.PaginationHTML(totalCount, itemsPerPage), // pagination list
                MaxPage = totalCount % itemsPerPage == 0 ? totalCount / itemsPerPage : totalCount / itemsPerPage + 1, // max page number
                ItemsPerPage = itemsPerPage
            };

            return Json(indexHTML, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Form Manager Function Controller
        /// <summary>依照參數選擇是新增表單或者編輯表單</summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult EditForm(string id)
        {
            // Set Drop Down List
            ViewBag.SelectList = DALFunctions.QusetionsType();
            ViewBag.FrequenQList = DALFunctions.frequenQList();

            try
            {
                // Create New Form
                if (id == "NewForm")
                {
                    // New FID
                    Guid newID = Guid.NewGuid();

                    // Set View Data
                    ViewData["EditType"] = "New";
                    ViewData["InfoData"] = new FormInfo() { FormID = newID };
                    ViewData["LayoutData"] = new FormLayout() { FormID = newID };

                    // Reset Session
                    Session["FID"] = newID;
                    Session["EditType"] = "New";
                    Session["FormInfo"] = null;
                    Session["LayoutList"] = null;
                    Session["EditLayoutIndex"] = null;
                }
                else
                {
                    // Reset Session
                    Guid.TryParse(id, out Guid fid);

                    // Get Data from DB
                    FormInfo selectFIDInfo = DALFunctions.GetFormInfoByFID(fid);
                    List<FormLayout> selectFIDLayout = DALFunctions.GetFormLayoutByFID(fid);

                    // Set View Data
                    ViewData["EditType"] = fid;
                    ViewData["InfoData"] = selectFIDInfo;
                    ViewData["LayoutData"] = new FormLayout() { FormID = fid };

                    // Set Session
                    Session["FID"] = fid;
                    Session["EditType"] = null;
                    Session["FormInfo"] = selectFIDInfo;
                    Session["LayoutList"] = selectFIDLayout;
                    Session["EditLayoutIndex"] = null;
                }

                return View();
            }
            catch (Exception ex)
            {
                return RedirectToAction("ErrorPage", "Home", new { errMsg = ex.ToString() });
            }
        }

        /// <summary>從DB刪除所選的表單與相關的資料</summary>
        /// <param name="chkForm"></param>
        /// <returns></returns>
        public ActionResult DeleteForm(string[] chkForm)
        {
            try
            {
                DALFunctions.DeleteForms(chkForm);
                return RedirectToAction("FormManager");
            }
            catch (Exception ex)
            {
                return RedirectToAction("ErrorPage", "Home", new { errMsg = ex.ToString() });
            }
        }
        #endregion

        #region New Form and Edit Form
        /// <summary>換頁時儲存表單資訊</summary>
        /// <param name="ajaxData"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SaveInfoData(FormInfo ajaxData)
        {
            // Save into Session
            Session["FormInfo"] = ajaxData;

            // Set select List
            ViewBag.SelectList = DALFunctions.QusetionsType();

            // Set View Data
            ViewData["InfoData"] = (Session["FormInfo"] != null) ? Session["FormInfo"] : new FormInfo();
            ViewData["LayoutData"] = (Session["FormLayout"] != null) ? Session["FormLayout"] : new FormLayout();

            return Content("InfoSaved");
        }

        /// <summary>新表單問題列表</summary>
        /// <param name="fLay"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ShowLayout()
        {
            try
            {
                // Check session data exist
                List<FormLayout> list = (Session["LayoutList"] != null) ? (List<FormLayout>)Session["LayoutList"] : new List<FormLayout>();
                Guid.TryParse(Session["FID"].ToString(), out Guid fid);
                Session["LayoutList"] = list;

                // generate html code and return to page
                return Content(ModelFunctions.LayoutListHTML(list));
            }
            catch (Exception ex)
            {
                return RedirectToAction("ErrorPage", "Home", new { errMsg = ex.ToString() });
            }
        }

        /// <summary>新增表單問題列表</summary>
        /// <param name="fLay"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult NewLayout(FormLayout fLay)
        {
            try
            {
                // Check session data exist
                List<FormLayout> list = (Session["LayoutList"] != null) ? (List<FormLayout>)Session["LayoutList"] : new List<FormLayout>();
                Guid.TryParse(Session["FID"].ToString(), out Guid fid);
                fLay.FormID = fid;

                // Check is edit or new layout
                if (Session["EditLayoutIndex"] != null && int.TryParse(Session["EditLayoutIndex"].ToString(), out int LID))
                {
                    fLay.QuestionSort = LID + 1;
                    list[LID] = fLay;
                }
                else
                {
                    fLay.QuestionSort = (Session["LayoutList"] == null) ? 1 : list.Count() + 1;
                    // Add to list
                    list.Add(fLay);
                }

                // Save new list into session
                Session["LayoutList"] = list;
                Session["EditLayoutIndex"] = null;

FormSystem/FormSystem/Views/BackStage/AnsList.cshtml
@model List<FormSystem.Models.AnsInfo>
@{
    ViewBag.Title = "統計";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    div.Plot-placeholder {
        width: 550px;
        height: 450px;
    }
</style>
<script language="javascript" type="text/javascript" src="~/Scripts/flot/jquery.flot.min.js"></script>
<script language="javascript" type="text/javascript" src="~/Scripts/flot/jquery.flot.pie.js"></script>
<script type="text/javascript">
    var isPlot = false;
    function csvAjax() {
        // setup file name
        var queryString = new URLSearchParams(window.location.search);
        var fileName = queryString.get('formName') + ".csv";

        $.ajax({
            type: 'Get',
            url: '@Url.Action("ExportCSV")',
            success: function (result) {
                // setup csv format
                var csvString = "";
                result.forEach(function (arr1) {
                    arr1.forEach(function (arr2) {
                        csvString += arr2 + ",";
                    });
                    csvString += "\n";
                });

                // create object href
                var blob = new Blob([csvString], { type: "application/octet-stream" });
                var href = URL.createObjectURL(blob);

                // create download link
                var link = document.createElement("a");
                document.body.appendChild(link);

                // auto download
                link.href = href;
                link.download = fileName;
                link.click();
            }
        });
    };

    $(function () {
        // check is aleady plot
        if (!isPlot) {
            $.ajax({
                type: 'Get',
                url: '@Url.Action("../Home/PlotData")',
                success: function (result) {
                    var qBody = Object.keys(result);
                    var canvasHtml = '<p> </p>';

                    // create canvas
                    for (let i = 0; i < qBody.length; i++) {
                        var id = 'canvas' + i;
                        canvasHtml += `
                            <p>${qBody[i]}</p>
                            <div id="${id}" class="Plot-placeholder"></div>`;
                    }
                    canvasHtml += '<hr />';

                    $('#nav-plot').append(canvasHtml);

                    // draw on canvas
                    for (var i = 0; i < qBody.length; i++) {
                        var id = 'canvas' + i;
                        $.plot(`#${id}`, result[qBody[i]], {
                            series: {
                                pie: {
                                    show: true,
                                    radius: 3 / 4,
                                    label: {
                                        show: true,
                                        radius: 3 / 4,
                                        formatter: function (label, series) {
                                            return '<div style="font-size:8pt;text-align:center;padding:2px;color:white;">' + label + '<br/>' + Math.round(series.percent) + '%</div>';
                                        },
                                        background: {
                                            opacity: 0.5,
                                            color: '#000'
                                        }
                                    }
                                }
                            }
                        });
                    }

                    // set is plot
                    isPlot = true;
                }
            });
        }
    });
</script>

<h1>後台 - 統計</h1>
<hr />
@if (this.Model.Count() > 0)
{
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <button class="nav-link active" id="nav-list-tab" data-bs-toggle="tab" data-bs-target="#nav-list" type="button" role="tab" aria-controls="nav-list" aria-selected="true">回答清單</button>
            <button class="nav-link" id="nav-plot-tab" data-bs-toggle="tab" data-bs-target="#nav-plot" type="button" role="tab" aria-controls="nav-plot" aria-selected="false">分析圖表</button>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-list" role="tabpanel" aria-labelledby="nav-list-tab">
            <p><!--spacer--></p>
            <button class="btn btn-outline-success" id="getCSV" onclick="csvAjax()">取得.csv檔案</button>
            <p><!--spacer--></p>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">建立日期</th>
                        <th scope="col">名稱</th>
                        <th scope="col">詳細資料</th>
                    </tr>
                </thead>
                <tbody id="ListTBody">
                    @for (int i = 0; i < this.Model.Count(); i++)
                    {
                        int index = i + 1;
                        <tr>
                            <th>@index </th>
                            <td>@this.Model[i].CreateDate</td>
                            <td>@this.Model[i].AnsHead</td>
                            <td>@Html.ActionLink("前往", "HistoryAns", "Home", new { fid = this.Model[i].FormID, dataID = this.Model[i].DataID }, null)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="tab-pane fade" id="nav-plot" role="tabpanel" aria-labelledby="nav-plot-tab">
            <!--圖表放這裡-->
        </div>
    </div>
}
else
{
    <p>此表單尚無資料</p>
}
<input type="button" class="btn btn-outline-secondary" name="redirect" value="回上頁" onclick="javascript:window.history.back(-1);return false;" />

FormSystem/FormSystem/Views/BackStage/EditForm.cshtml
@{
    ViewBag.Title = "編輯表單";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string startDate = ((FormSystem.DBModel.FormInfo)ViewData["InfoData"]).StartDate.ToString("yyyy-MM-dd");
    string endDate = ((FormSystem.DBModel.FormInfo)ViewData["InfoData"]).EndDate.ToString("yyyy-MM-dd");
}

<script>
    // Set layout edit ajax function
    function EditLayoutAjax(index) {
        var LID = 'LayoutIndex = ' + index;
        $.ajax({
            type: 'POST',
            url: '@Url.Action("EditLayout")',
            data: LID,
            success: function (result) {
                $('#inputDescribe').val(result['Body']);
                $('#inputAns').val(result['Answer']);
                $('#selectType').val(result['QuestionType']);
                $('#checkNullable').attr('checked', result['NeedAns']);
            }
        })
    };

    $(document).ready(function () {
        // Get page's type and bypass function
        var setType = '@ViewData["EditType"].ToString()';
        if (setType != 'New') {
            $("#StartDate").val("@startDate")
            $("#EndDate").val("@endDate")

            $.ajax({
                type: 'POST',
                url: '@Url.Action("ShowLayout")',
                success: function (result) { $('#qTable').append(result) }
            });
        }

        // create info data save function
        function SaveInfoPage() {
            $('#InfoForm').submit(
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("SaveInfoData")',
                    data: $('#InfoForm').serialize(),
                    success: function (result) { }
                })
            );
        };

        // click nav-tab and save infomation into session
        $("#nav-layout-tab").click(SaveInfoPage);
        $("#nav-view-tab").click(SaveInfoPage);

        // Chose frequent question and show question data
        $('#freqQselect').change(function () {
            var formatData = 'frequenQ = ' + $('#freqQselect').val();
            $('#freqQListForm').submit(
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("ShowFreqQInfo")',
                    data: formatData,
                    success: function (result) {
                        console.log(result);
                        $('#inputDescribe').val(result['Body']);
                        $('#inputAns').val(result['Answer']);
                        $('#selectType').val(result['QuestionType']);
                        $('#checkNullable').attr('checked', result['NeedAns']);
                    }
                })
            );
        });
    });
</script>
<!--Title-->
<div class="headTitle">
    <h1>後台 - 編輯表單</h1>
</div>
<hr />
<!--Edit Area-->
<nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <button class="nav-link active" id="nav-info-tab" data-bs-toggle="tab" data-bs-target="#nav-Info" type="button" role="tab" aria-controls="nav-home" aria-selected="true">問卷</button>
        <button class="nav-link" id="nav-layout-tab" data-bs-toggle="tab" data-bs-target="#nav-Layout" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">問題</button>
        <a class="nav-link" id="nav-view-tab" data-bs-toggle="tab" data-bs-target="#nav-View" type="button" role="tab" aria-controls="nav-contact" aria-selected="false" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#reviewForm" href="@Url.Action("ShowForm")">檢視表單</a>
    </div>
</nav>
<!--Page Start Here-->
<div class="tab-content" id="nav-tabContent">
    <!--問卷-->
    <div class="tab-pane fade show active" id="nav-Info" role="tabpanel" aria-labelledby="nav-home-tab">
        <p><!--排版用--></p>
        @{Html.RenderPartial("../PartialView/_NewInfo", ViewData["InfoData"]);}
    </div>
    <!--問題-->
    <div class="tab-pane fade" id="nav-Layout" role="tabpanel" aria-labelledby="nav-profile-tab">
        <p><!--排版用--></p>
        <!--預設問題div-->
        <div class="mb-3 row">
            <label for="selectType" class="col-sm-1 col-form-label" style="text-align:right">種類:</label>
            <div class="col-sm-3">
                @Html.DropDownList("frequenQ", (IEnumerable<SelectListItem>)ViewBag.FrequenQList, new { @class = "form-select", @id = "freqQselect" })
            </div>
        </div>
        @{Html.RenderPartial("../PartialView/_NewLayout", ViewData["LayoutData"]);}
    </div>
    <!--檢視表單-->
    <div class="tab-pane fade" id="nav-View" role="tabpanel" aria-labelledby="nav-contact-tab">
        <p></p>
        <div id="reviewForm"></div>
        <!--確認送出-->
        <hr />
        <div>
            <a class="btn btn-outline-warning" id="saveFrom" href="/BackStage/SaveFormToDB" onclick="return confirm('確認送出?');">送出</a>
        </div>
    </div>
</div>

FormSystem/FormSystem/Views/BackStage/FormManager.cshtml
@model List<FormSystem.DBModel.FormInfo>
@{
    ViewBag.Title = "問卷管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string[] chkForm = new string[this.Model.Count];
}

<!--Script-->
<script>
    var currentPage = 1;
    var maxPageNum = 0;
    var itemPerPage = 10;
    var hideByPager = function (pager) {
        // Reset page
        $('.table tbody tr').hide();

        // hide rows
        for (var i = pager * itemPerPage - itemPerPage + 1; i <= pager * itemPerPage; i++) {
            $(`.table tbody tr:nth-child(${i})`).show();
        }

        // set current Page
        currentPage = pager;

        // set pager active
        $("li").toggleClass('active', false);
        $(`li:nth-child(${pager + 1})`).toggleClass('active', true);

        // set prvious button enable or disable
        if (currentPage == 1) {
            $('li:first').toggleClass('disabled', true);
        }
        else {
            $('li:first').toggleClass('disabled', false);
        }

        // set next button enable or disable
        if (currentPage == maxPageNum) {
            $('li:last').toggleClass('disabled', true);
        }
        else {
            $('li:last').toggleClass('disabled', false);
        }
    };
    var nextOrPrivous = function (type) {
        if (type === 'pre') {hideByPager(currentPage - 1); }
        if (type === 'next') {hideByPager(currentPage + 1); }
    };
    function searchForm() {
        // get element
        var searchName = document.getElementById("searchName");
        var searchSDate = document.getElementById("searchStartDate");
        var searchEDate = document.getElementById("searchEndDate");

        var nameFilter = searchName.value.toUpperCase();
        var table = document.getElementById("FormTable");
        var ul = document.getElementById("paginationArea");
        var tr = table.getElementsByTagName("tr");

        // hide pagination area
        ul.style.display = 'none';

        // loop each item and check argument
        for (i = 0; i < tr.length; i++) {
            // get need column
            var name_td = tr[i].getElementsByTagName("td")[1];
            var sDate_td = tr[i].getElementsByTagName("td")[3];
            var eDate_td = tr[i].getElementsByTagName("td")[4];

            // get column value or text
            var txtValue = name_td.textContent || name_td.innerText;
            var sDateValue = sDate_td.textContent || sDate_td.innerText;
            var eDateValue = eDate_td.textContent || eDate_td.innerText;

            // check argument is match or in range
            var nameMatch = txtValue.toUpperCase().indexOf(nameFilter) > -1
            var DateRange = sDateValue >= searchSDate.value && eDateValue <= searchEDate.value

            // show result
            if (nameMatch && DateRange) {
                tr[i].style.display = "";
            } else {
                tr[i].style.display = "none";
            }
        }
    }
    function resetSearch() {
        // reset all relate element
        document.getElementById("paginationArea").style.display = "";
        document.getElementById("searchName").value = "";
        document.getElementById("searchStartDate").value = "";
        document.getElementById("searchEndDate").value = "";

        // set to last page when start search
        hideByPager(currentPage);
    }

    $(document).ready(function () {
        // Get All Questions List HTML
        $.ajax({
            type: 'Get',
            url: '@Url.Action("FormManagerPagination")',
            success: function (result) {
                // pagination
                var pageHtml =
                    `<li class="page-item">
                        <a class="page-link" href="#" onclick="nextOrPrivous('pre')">上一頁</a>
                    </li>
                    ${result['PagniationHTML']}
                    <li class="page-item">
                        <a class="page-link" href="#" onclick="nextOrPrivous('next')">下一頁</a>
                    </li>`;
                $("#paginationArea").append(pageHtml);

                // set Page
                itemPerPage = result['ItemsPerPage'];
                hideByPager(1);
                currentPage = 1;
                maxPageNum = result['MaxPage'];
            }
        });
    });
</script>
<!--Title-->
<div class="jumbotron">
    <h1>後台 - 問卷管理</h1>
</div>
<hr />
<!--Search Area-->
<div class="container">
    <div class="row row-cols-3">
        <div class="col">
            <input class="form-control me-2" id="searchName" type="search" placeholder="搜尋問卷標題" aria-label="Search">
        </div>
        <div class="col"></div>
        <div class="col"></div>
        <div class="col">
            開始時間:
            <input class="form-control me-2" id="searchStartDate" type="date">
        </div>
        <div class="col">
            結束時間:
            <input class="form-control me-2" id="searchEndDate" type="date">
        </div>
        <div class="col">
            <button class="btn btn-outline-success" onclick="searchForm()">搜尋</button>
            <button class="btn btn-outline-danger" onclick="resetSearch()">清除</button>
        </div>
    </div>
</div>
<hr />
<!--Function List-->
<div class="row">
    @Html.ActionLink("新增表單", "EditForm", "BackStage", new { @id = "NewForm" }, new { @class = "btn btn-secondary" })
</div>
<hr />
<!--Form List-->
@using (Html.BeginForm("DeleteForm", "BackStage", FormMethod.Post, new { @id = "FormList" }))
{
    <div>
        <input class="btn btn-outline-danger" type="submit" value="刪除所選" onclick="return confirm('確認刪除?');">
    </div>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">#</th>
                <th scope="col">問卷名稱</th>
                <th scope="col">狀態</th>
                <th scope="col">開始時間</th>
                <th scope="col">結束時間</th>
                <th scope="col">統計</th>
            </tr>
        </thead>
        <tbody id="FormTable">
            @for (int i = 0; i < this.Model.Count; i++)
            {
                string num = (i + 1).ToString();
                string status = (DateTime.Now > this.Model[i].StartDate && DateTime.Now < this.Model[i].EndDate) ? "投票中" : "關閉中";
                <tr>
                    <td>@Html.CheckBox($"chkForm[{i}]", new { @value = this.Model[i].FormID })</td>
                    <th>@num</th>
                    <td>@Html.ActionLink(this.Model[i].Name, "EditForm", "BackStage", new { @id = this.Model[i].FormID }, null)</td>
                    <td>@status</td>
                    <td>@this.Model[i].StartDate.ToString("yyyy-MM-dd")</td>
                    <td>@this.Model[i].EndDate.ToString("yyyy-MM-dd")</td>
                    <td>@Html.ActionLink("前往", "AnsList", "BackStage", new { fid = this.Model[i].FormID, formName = this.Model[i].Name }, null)</td>
                </tr>
            }
        </tbody>
    </table>
}
<!--Pagination-->
<nav aria-label="Index Page navigation">
    <ul class="pagination" id="paginationArea">
        <!--Put pagination here-->
    </ul>
</nav>

<script type="text/javascript">
    $("#FormList").on("submit", function () {
        return confirm("確認刪除選擇的表單嗎?");
    });
</script>